(function () {
  'use strict';
  var announcements = [];
  var activeType = 'all';
  function esc(value) { return String(value || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
  function canSee(item, profile) { if (!profile) return false; if (item.type === 'system' && (profile.role === 'admin' || profile.department === '测试')) return true; return item.audience === 'all' || item.audience === profile.department; }
  function canSee(item, profile) { return profile && (item.audience === 'all' || profile.role === 'admin' || profile.department === '测试' || item.audience === profile.department); }
  function render() { var list = document.getElementById('announcementList'); var profile = window.PATCHWORK_PROFILE; var visible = announcements.filter(function (item) { return (activeType === 'all' || activeType === item.type) && canSee(item, profile); }); list.innerHTML = visible.map(function (item) { var detail = '<a class="announcement-detail-link" href="announcement-detail.html?id=' + encodeURIComponent(item.id) + '">查看详情</a>'; var label = item.type === 'system' ? '系统公告' : '管理员公告'; return '<article class="announcement-card announcement-' + item.type + '"><span class="announcement-badge">' + esc(item.badge) + '</span><div class="announcement-body"><small class="announcement-type">' + label + ' · ' + esc(item.audience || '全体') + '</small><h2>' + esc(item.title) + '</h2><p>' + esc(item.content).replace(/\n/g, '<br>') + '</p><div class="announcement-meta"><span>' + esc(new Date(item.created_at).toLocaleDateString('zh-CN')) + '</span><span>' + esc(item.type === 'system' ? '系统自动公告' : '管理员公告') + '</span><span>发布人：' + esc(item.author_name || '系统') + '</span>' + detail + '</div></div></article>'; }).join('') || '<div class="cases-empty">暂无当前账号可查看的公告</div>'; }
  async function setup() { var profile = window.PATCHWORK_PROFILE; var canPublish = profile && (profile.role === 'admin' || profile.role === 'leader'); var publishButton = document.getElementById('publishAnnouncement'); if (canPublish) publishButton.classList.remove('hidden'); publishButton.onclick = function () { document.getElementById('publishAnnouncementModal').classList.remove('hidden'); }; document.getElementById('closePublishAnnouncement').onclick = closeModal; document.getElementById('cancelPublishAnnouncement').onclick = closeModal; document.getElementById('publishAnnouncementModal').onclick = function (event) { if (event.target === event.currentTarget) closeModal(); }; document.querySelectorAll('.announcement-tab').forEach(function (button) { button.onclick = function () { activeType = button.dataset.type; document.querySelectorAll('.announcement-tab').forEach(function (item) { item.classList.remove('active'); }); button.classList.add('active'); render(); }; }); document.getElementById('publishAnnouncementForm').onsubmit = async function (event) { event.preventDefault(); if (!canPublish) return; var data = Object.fromEntries(new FormData(event.currentTarget).entries()); try { var result = await window.PatchworkAPI.createAnnouncement({ type: 'manual', audience: data.audience, badge: '公告', title: data.title, content: data.content, author_id: profile.id, author_name: profile.full_name || profile.username }); announcements.unshift(result[0]); closeModal(); event.currentTarget.reset(); render(); } catch (error) { document.getElementById('publishAnnouncementError').textContent = error.message || '发布公告失败。'; document.getElementById('publishAnnouncementError').classList.remove('hidden'); } }; try { announcements = await window.PatchworkAPI.listAnnouncements(); render(); } catch (error) { document.getElementById('announcementList').innerHTML = '<div class="cases-empty">公告加载失败：' + esc(error.message) + '</div>'; } }
  function closeModal() { document.getElementById('publishAnnouncementModal').classList.add('hidden'); }
  window.PATCHWORK_READY.then(setup);
})();
