(function () {
  'use strict';
  var bugId = new URLSearchParams(location.search).get('bug'), viewDepartment = new URLSearchParams(location.search).get('department'), bug, members = [];
  var statusText = { open: '待处理', in_progress: '处理中', resolved: '已解决' }, importanceText = { heavy: '严重', medium: '一般', light: '轻微' };
  function ensureAssigneeModal() {
    if (!document.getElementById('assigneeModal')) {
      var modal = document.createElement('div'); modal.id = 'assigneeModal'; modal.className = 'modal-backdrop hidden'; modal.innerHTML = '<section class="user-modal assignee-modal"><div class="developer-modal-header"><div><h2>指定跟进人</h2><p id="assigneeBugInfo" class="user-modal-identity"></p><p class="user-modal-help">本部门所有成员均可指定或修改跟进人。</p></div><button id="closeAssigneeModal" class="icon-button" type="button">×</button></div><div class="assignee-form"><label class="field"><span>跟进人</span><select id="assigneeSelect"><option value="">请选择本部门成员</option></select></label><p id="currentAssigneeHint" class="user-modal-help"></p><p id="assigneeError" class="login-error hidden"></p><div class="edit-user-actions"><button id="cancelAssignee" class="user-cancel-button" type="button">取消</button><button id="confirmAssignee" class="case-action-button" type="button">确认指定</button></div></div></section>'; document.body.appendChild(modal);
    }
    if (!document.getElementById('statusModal')) { var statusModal = document.createElement('div'); statusModal.id = 'statusModal'; statusModal.className = 'modal-backdrop hidden'; statusModal.innerHTML = '<section class="user-modal assignee-modal"><div class="developer-modal-header"><div><h2>更改当前状态</h2><p id="statusBugInfo" class="user-modal-identity"></p><p class="user-modal-help">仅当前指定跟进人可提交状态变更。</p></div><button id="closeStatusModal" class="icon-button" type="button">×</button></div><div class="assignee-form"><label class="field"><span>当前状态</span><select id="statusSelect"><option value="open">待处理</option><option value="in_progress">处理中</option><option value="resolved">已完成</option></select></label><p class="user-modal-help">可选：待处理 / 处理中 / 已完成</p><p id="statusError" class="login-error hidden"></p><div class="edit-user-actions"><button id="cancelStatus" class="user-cancel-button" type="button">取消</button><button id="confirmStatus" class="case-action-button" type="button">确认更改</button></div></div></section>'; document.body.appendChild(statusModal); }
    if (!document.getElementById('transferModal')) { var transferModal = document.createElement('div'); transferModal.id = 'transferModal'; transferModal.className = 'modal-backdrop hidden'; transferModal.innerHTML = '<section class="user-modal assignee-modal"><div class="developer-modal-header"><div><h2>转组</h2><p id="transferBugInfo" class="user-modal-identity"></p><p class="user-modal-help">仅当前所属部门组长或超级管理员可发起转组；系统将记录原部门、目标部门、转组人、时间和原因。</p></div><button id="closeTransferModal" class="icon-button" type="button">×</button></div><div class="assignee-form"><label class="field"><span>新归属部门 <i>*</i></span><select id="transferDepartment"><option value="">请选择新部门</option></select></label><label class="field"><span>转组原因（选填）</span><textarea id="transferReason" rows="4" placeholder="请说明转组原因"></textarea></label><p id="transferError" class="login-error hidden"></p><div class="edit-user-actions"><button id="cancelTransfer" class="user-cancel-button" type="button">取消</button><button id="confirmTransfer" class="case-action-button" type="button">确认转组</button></div></div></section>'; document.body.appendChild(transferModal); }
    if (!document.getElementById('transferModal')) { var transferModal = document.createElement('div'); transferModal.id = 'transferModal'; transferModal.className = 'modal-backdrop hidden'; transferModal.innerHTML = '<section class="user-modal assignee-modal"><div class="developer-modal-header"><div><h2>转组</h2><p id="transferBugInfo" class="user-modal-identity"></p><p class="user-modal-help">仅当前所属部门组长或超级管理员可发起转组；系统将记录原部门、目标部门、转组人、时间和原因。</p></div><button id="closeTransferModal" class="icon-button" type="button">×</button></div><div class="assignee-form"><label class="field"><span>新归属部门 <i>*</i></span><select id="transferDepartment"><option value="">请选择新部门</option></select></label><label class="field"><span>转组原因（选填）</span><textarea id="transferReason" rows="4" placeholder="请说明转组原因"></textarea></label><p id="transferError" class="login-error hidden"></p><div class="edit-user-actions"><button id="cancelTransfer" class="user-cancel-button" type="button">取消</button><button id="confirmTransfer" class="case-action-button" type="button">确认转组</button></div></div></section>'; document.body.appendChild(transferModal); }
  }
  function esc(v) { return String(v == null ? '' : v).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
  function date(v) { return v ? new Date(v).toLocaleString('zh-CN') : '—'; }
  function extension(url) { var clean = String(url || '').split('?')[0].split('#')[0]; var name = clean.slice(clean.lastIndexOf('/') + 1); var match = name.match(/(\.[a-z0-9]+)$/i); return match ? match[1].toLowerCase() : ''; }
  function category(url) { var ext = extension(url); if (['.png', '.jpg', '.jpeg', '.gif', '.webp', '.bmp', '.avif', '.svg'].includes(ext)) return 'image'; if (['.doc', '.docx', '.pdf', '.md', '.txt', '.rtf', '.ppt', '.pptx'].includes(ext)) return 'document'; if (['.xls', '.xlsx', '.csv', '.ods'].includes(ext)) return 'sheet'; return 'other'; }
  function attachmentSummary(urls, code) { if (!urls.length) return '无附件'; var kind = urls.length === 1 ? category(urls[0]) : 'other'; var label = urls.length === 1 && kind === 'image' ? '1 张图片' : urls.length === 1 && kind === 'document' ? '1 份文档' : urls.length === 1 && kind === 'sheet' ? '1 份表格' : urls.length + ' 个附件'; var links = urls.map(function (url, index) { var filename = code + '-' + String(index + 1).padStart(2, '0') + extension(url); return '<a class="detail-attachment-download" href="' + esc(url) + '" download="' + filename + '" target="_blank" rel="noopener">下载附件 ' + String(index + 1).padStart(2, '0') + '</a>'; }).join(''); return '<span>' + label + '</span><span class="detail-attachment-links">' + links + '</span>'; }
  function toast(t, type) { var n = document.getElementById('toast'); n.textContent = t; n.className = 'toast show ' + (type || ''); setTimeout(function () { n.className = 'toast'; }, 3000); }
  function canManage() { var p = window.PATCHWORK_PROFILE; return p && (p.role === 'admin' || (p.role === 'leader' && p.department === (viewDepartment || bug.assignee_department))); }
  function render() {
    var p = window.PATCHWORK_PROFILE, current = viewDepartment || (p && p.department) || bug.assignee_department;
    document.title = '校缘宝内测管理网站 · ' + (bug.bug_no ? 'BUG-' + String(bug.bug_no).padStart(4, '0') : '缺陷详情');
    document.getElementById('detailCode').textContent = bug.bug_no ? 'BUG-' + String(bug.bug_no).padStart(4, '0') : 'BUG-0001'; document.getElementById('detailTitle').textContent = bug.title;
    document.getElementById('detailReporter').textContent = bug.reporter || '—'; document.getElementById('detailCreated').textContent = date(bug.created_at); document.getElementById('detailDepartment').textContent = bug.assignee_department || '—';
    document.getElementById('detailModule').textContent = bug.module || '—'; document.getElementById('detailDescription').textContent = bug.description || '—'; document.getElementById('detailSteps').textContent = bug.repro_steps || '—'; document.getElementById('detailExpected').textContent = bug.expected_result || '—'; document.getElementById('detailActual').textContent = bug.actual_result || '—'; document.getElementById('detailImportance').textContent = importanceText[bug.importance] || bug.importance || '—'; var code = bug.bug_no ? 'BUG-' + String(bug.bug_no).padStart(4, '0') : 'BUG-0001'; document.getElementById('detailAttachments').innerHTML = attachmentSummary(bug.attachment_urls || [], code);
    document.getElementById('detailAssignee').textContent = bug.assignee || '—'; document.getElementById('detailContact').textContent = '联系提交人'; document.getElementById('detailStatus').textContent = statusText[bug.status] || bug.status || '—'; document.getElementById('detailNote').textContent = bug.transfer_note || bug.fix_plan || '暂无备注';
    var note = current === '测试' ? '测试普通成员可查看；指定跟进人和转组仅测试组长、超级管理员可操作。' : current + '成员可指定跟进人与处理；转组仅本部门组长、超级管理员可操作。'; document.getElementById('permissionNote').textContent = note;
    var admin = p && p.role === 'admin', leader = p && p.role === 'leader' && p.department === current, assignee = p && bug.assignee_id === p.id, testView = current === '测试';
    var assigneeButton = document.getElementById('assigneeButton'); var transferButton = document.getElementById('transferButton'); var statusButton = document.getElementById('statusButton');
    var canOperate = Boolean(admin || leader || assignee);
    assigneeButton.classList.toggle('hidden', testView || !(admin || leader));
    transferButton.classList.toggle('hidden', testView || !(admin || leader));
    statusButton.classList.toggle('hidden', testView || !canOperate);
    document.getElementById('noteButton').classList.toggle('hidden', !testView && !canOperate);
    assigneeButton.disabled = !(admin || leader);
    transferButton.disabled = !(admin || leader);
    statusButton.disabled = !canOperate;
  }
  function actionPanel(type) { var panel = document.getElementById('detailActionPanel'); var input = document.getElementById('actionInput'); var note = document.getElementById('detailNote'); if (type === 'note') { note.innerHTML = '<textarea id="inlineNoteInput" class="inline-note-input" rows="5">' + esc(bug.transfer_note || bug.fix_plan || '') + '</textarea><div class="inline-note-actions"><button id="cancelInlineNote" class="user-cancel-button" type="button">取消</button><button id="saveInlineNote" class="case-action-button" type="button">保存备注</button></div>'; document.getElementById('cancelInlineNote').onclick = function () { render(); }; document.getElementById('saveInlineNote').onclick = saveInlineNote; return; } panel.dataset.type = type; input.value = ''; input.placeholder = '请输入新的处理信息'; panel.classList.remove('hidden'); input.focus(); }
  async function saveInlineNote() { var input = document.getElementById('inlineNoteInput'), button = document.getElementById('saveInlineNote'); if (!input) return; button.disabled = true; button.textContent = '保存中…'; try { var updated = await window.PatchworkAPI.updateBug(bug.id, { transfer_note: input.value.trim() }); bug = updated[0] || Object.assign({}, bug, { transfer_note: input.value.trim() }); render(); toast('处理备注已更新。', 'success'); } catch (e) { toast(e.message || '保存备注失败。', 'error'); } finally { button.disabled = false; button.textContent = '保存备注'; } }
  function bugLabel() { return (bug.bug_no ? 'BUG-' + String(bug.bug_no).padStart(4, '0') : 'BUG-0001') + '｜' + bug.title; }
  function openStatusModal() { document.getElementById('statusBugInfo').textContent = bugLabel(); document.getElementById('statusSelect').value = bug.status === 'resolved' ? 'resolved' : bug.status; document.getElementById('statusModal').classList.remove('hidden'); }
  function closeStatusModal() { document.getElementById('statusModal').classList.add('hidden'); }
  async function confirmStatus() { var button = document.getElementById('confirmStatus'), value = document.getElementById('statusSelect').value; button.disabled = true; button.textContent = '保存中…'; try { var updated = await window.PatchworkAPI.updateBug(bug.id, { status: value }); bug = updated[0] || Object.assign({}, bug, { status: value }); closeStatusModal(); render(); toast('当前状态已更新。', 'success'); } catch (e) { document.getElementById('statusError').textContent = e.message || '状态更新失败。'; document.getElementById('statusError').classList.remove('hidden'); } finally { button.disabled = false; button.textContent = '确认更改'; } }
  function openTransferModal() { var current = bug.assignee_department, select = document.getElementById('transferDepartment'), targets = ['技术—前端', '技术—后端', '设计', '产品'].filter(function (item) { return item !== current; }); document.getElementById('transferBugInfo').textContent = bugLabel(); select.innerHTML = '<option value="">请选择新部门</option>' + targets.map(function (item) { return '<option value="' + esc(item) + '">' + item + '</option>'; }).join(''); document.getElementById('transferReason').value = ''; document.getElementById('transferModal').classList.remove('hidden'); }
  function closeTransferModal() { document.getElementById('transferModal').classList.add('hidden'); }
  async function confirmTransfer() { var target = document.getElementById('transferDepartment').value, reason = document.getElementById('transferReason').value.trim(), error = document.getElementById('transferError'), button = document.getElementById('confirmTransfer'), session = (await window.PATCHWORK_AUTH.getSession()).data.session, oldDepartment = bug.assignee_department || ''; if (!target) { error.textContent = '请选择新归属部门。'; error.classList.remove('hidden'); return; } button.disabled = true; button.textContent = '提交中…'; try { await window.PatchworkAPI.updateBug(bug.id, { assignee_department: target, transfer_from: oldDepartment, transfer_note: reason, assigned_at: new Date().toISOString() }); await window.PatchworkAPI.createAssignmentEvent({ bug_id: bug.id, from_department: oldDepartment, to_department: target, from_user_id: bug.follow_up_id || null, to_user_id: null, note: reason, created_by: session.user.id }); bug.assignee_department = target; bug.transfer_from = oldDepartment; bug.transfer_note = reason; closeTransferModal(); render(); toast('转组已完成，系统已记录流转日志。', 'success'); } catch (e) { error.textContent = e.message || '转组失败。'; error.classList.remove('hidden'); } finally { button.disabled = false; button.textContent = '确认转组'; } }
  async function saveAction() { var type = document.getElementById('detailActionPanel').dataset.type, value = document.getElementById('actionInput').value.trim(), patch = {}; if (type === 'note') patch.transfer_note = value; else if (type === 'status') patch.status = value || bug.status; else if (type === 'assignee') patch.assignee = value; else patch.transfer_note = value; try { var updated = await window.PatchworkAPI.updateBug(bug.id, patch); bug = updated[0] || Object.assign({}, bug, patch); render(); document.getElementById('detailActionPanel').classList.add('hidden'); toast('缺陷信息已更新。', 'success'); } catch (e) { toast(e.message || '更新失败。', 'error'); } }
  function openAssigneeModal() { var select = document.getElementById('assigneeSelect'); if (!select) return; var department = bug.assignee_department; select.innerHTML = '<option value="">请选择本部门成员</option>' + members.filter(function (item) { return item.department === department; }).map(function (item) { return '<option value="' + esc(item.id) + '">' + esc(item.full_name || item.username) + '</option>'; }).join(''); select.value = bug.assignee_id || ''; document.getElementById('assigneeBugInfo').textContent = (bug.bug_no ? 'BUG-' + String(bug.bug_no).padStart(4, '0') : 'BUG-0001') + '｜' + bug.title; document.getElementById('currentAssigneeHint').textContent = '当前跟进人：' + (bug.assignee || '—') + '（' + department + '部门）'; document.getElementById('assigneeModal').classList.remove('hidden'); }
  function closeAssigneeModal() { document.getElementById('assigneeModal').classList.add('hidden'); }
  async function confirmAssignee() { var selectedId = document.getElementById('assigneeSelect').value, selected = members.find(function (item) { return item.id === selectedId; }), error = document.getElementById('assigneeError'), button = document.getElementById('confirmAssignee'); if (!selected) { error.textContent = '请选择本部门成员。'; error.classList.remove('hidden'); return; } button.disabled = true; button.textContent = '保存中…'; try { var name = selected.full_name || selected.username; var updated = await window.PatchworkAPI.updateBug(bug.id, { assignee_id: selected.id, follow_up_id: selected.id, assignee: name, assigned_at: new Date().toISOString() }); bug = updated[0] || Object.assign({}, bug, { assignee_id: selected.id, follow_up_id: selected.id, assignee: name }); closeAssigneeModal(); render(); toast('跟进人已更新。', 'success'); } catch (e) { error.textContent = e.message || '指定跟进人失败。'; error.classList.remove('hidden'); } finally { button.disabled = false; button.textContent = '确认指定'; } }
  async function load() { try { await window.PATCHWORK_READY; var result = await Promise.all([window.PatchworkAPI.listBugs(), window.PatchworkAPI.listProfiles()]); bug = result[0].find(function (item) { return item.id === bugId; }); members = result[1] || []; if (!bug) throw new Error('找不到该缺陷。'); render(); } catch (e) { toast(e.message, 'error'); } }
  ensureAssigneeModal(); document.getElementById('noteButton').onclick = function () { actionPanel('note'); }; document.getElementById('assigneeButton').onclick = openAssigneeModal; document.getElementById('statusButton').onclick = openStatusModal; document.getElementById('transferButton').onclick = openTransferModal; document.getElementById('cancelAction').onclick = function () { document.getElementById('detailActionPanel').classList.add('hidden'); }; document.getElementById('saveAction').onclick = saveAction; document.getElementById('closeAssigneeModal').onclick = closeAssigneeModal; document.getElementById('cancelAssignee').onclick = closeAssigneeModal; document.getElementById('confirmAssignee').onclick = confirmAssignee; document.getElementById('assigneeModal').onclick = function (event) { if (event.target === event.currentTarget) closeAssigneeModal(); }; document.getElementById('closeStatusModal').onclick = closeStatusModal; document.getElementById('cancelStatus').onclick = closeStatusModal; document.getElementById('confirmStatus').onclick = confirmStatus; document.getElementById('closeTransferModal').onclick = closeTransferModal; document.getElementById('cancelTransfer').onclick = closeTransferModal; document.getElementById('confirmTransfer').onclick = confirmTransfer; load();
})();
