-- 为历史缺陷补充从 0001 开始的连续编号。
alter table public.bugs add column if not exists bug_no bigint generated by default as identity;

create unique index if not exists bugs_bug_no_key on public.bugs (bug_no);

notify pgrst, 'reload schema';

select id, bug_no, title
from public.bugs
order by bug_no;
