-- WARNING: this migration intentionally removes the old bug data.
-- Execute once in Supabase SQL Editor before using the new report form.

drop table if exists public.bug_reports cascade;
drop table if exists public.bugs cascade;

create table public.bug_reports (
  id uuid primary key default gen_random_uuid(),
  bug_no bigint generated by default as identity unique,
  title text not null check (char_length(title) between 1 and 120),
  description text not null check (char_length(description) between 1 and 3000),
  reporter text not null check (char_length(reporter) between 1 and 40),
  submitter_id uuid references auth.users(id),
  module text not null check (char_length(module) between 1 and 60),
  environment text not null default '',
  importance text not null check (importance in ('light', 'medium', 'heavy')),
  repro_steps text not null check (char_length(repro_steps) between 1 and 3000),
  expected_result text not null default '',
  actual_result text not null default '',
  attachment_urls text[] not null default '{}',
  assignee_department text not null check (assignee_department in ('技术—前端', '技术—后端', '设计', '产品')),
  assignee text not null default '',
  assignee_id uuid references auth.users(id),
  follow_up_id uuid references auth.users(id),
  status text not null default 'open' check (status in ('open', 'in_progress', 'resolved')),
  fix_plan text not null default '',
  transfer_from text not null default '',
  transfer_note text not null default '',
  target_date date,
  resolved_at timestamptz,
  assigned_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.bug_reports enable row level security;

create policy "team read bug reports" on public.bug_reports
  for select to authenticated using (true);

create policy "team create bug reports" on public.bug_reports
  for insert to authenticated with check (submitter_id = auth.uid());

create policy "team update bug reports" on public.bug_reports
  for update to authenticated
  using (
    submitter_id = auth.uid()
    or assignee_id = auth.uid()
    or follow_up_id = auth.uid()
    or public.is_admin()
    or public.current_department() = assignee_department
  )
  with check (true);

create index bug_reports_department_idx on public.bug_reports (assignee_department);
create index bug_reports_status_idx on public.bug_reports (status);
create index bug_reports_created_at_idx on public.bug_reports (created_at desc);

notify pgrst, 'reload schema';
