-- 在 Supabase SQL Editor 中执行本文件。
create extension if not exists pgcrypto;

-- Team identity and role model. Create matching auth.users accounts in Supabase Auth.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  full_name text not null,
  employee_no text not null unique,
  department text not null check (department in ('管理', '测试', '技术—前端', '技术—后端', '设计', '产品')),
  role text not null default 'member' check (role in ('member', 'leader', 'admin')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin' and active); $$;

create or replace function public.current_department()
returns text language sql stable security definer set search_path = public
as $$ select department from public.profiles where id = auth.uid() and active; $$;

create table if not exists public.bugs (
  id uuid primary key default gen_random_uuid(),
  bug_no bigint generated by default as identity unique,
  title text not null check (char_length(title) between 1 and 120),
  description text not null check (char_length(description) between 1 and 3000),
  reporter text not null check (char_length(reporter) between 1 and 40),
  module text not null check (char_length(module) between 1 and 60),
  environment text not null default '' check (char_length(environment) <= 200),
  importance text not null default 'medium' check (importance in ('light', 'medium', 'heavy')),
  repro_steps text not null check (char_length(repro_steps) between 1 and 3000),
  expected_result text not null default '' check (char_length(expected_result) <= 1500),
  actual_result text not null default '' check (char_length(actual_result) <= 1500),
  attachment_urls text[] not null default '{}',
  status text not null default 'open' check (status in ('open', 'in_progress', 'resolved')),
  fix_plan text not null default '' check (char_length(fix_plan) <= 3000),
  assignee text not null default '' check (char_length(assignee) <= 40),
  target_date date,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.bugs add column if not exists bug_no bigint generated by default as identity;
create unique index if not exists bugs_bug_no_key on public.bugs (bug_no);

alter table public.bugs add column if not exists submitter_id uuid references auth.users(id);

alter table public.bugs add column if not exists transfer_from text not null default '';
alter table public.bugs add column if not exists transfer_note text not null default '';
alter table public.bugs add column if not exists follow_up_id uuid references auth.users(id);
alter table public.bugs add column if not exists assigned_at timestamptz;

create table if not exists public.test_cases (
  id uuid primary key default gen_random_uuid(),
  case_no bigint generated by default as identity unique,
  title text not null check (char_length(title) between 1 and 160),
  module text not null check (char_length(module) between 1 and 80),
  preconditions text not null default '',
  steps text not null check (char_length(steps) between 1 and 4000),
  expected_result text not null check (char_length(expected_result) between 1 and 3000),
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high')),
  status text not null default 'submitted' check (status in ('submitted', 'reviewing', 'approved', 'rejected')),
  submitter_id uuid not null references auth.users(id),
  reviewer_id uuid references auth.users(id),
  review_note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.test_cases add column if not exists file_name text;
alter table public.test_cases add column if not exists file_url text;
alter table public.test_cases add column if not exists file_type text;
alter table public.test_cases add column if not exists note text not null default '';

create table if not exists public.assignment_events (
  id uuid primary key default gen_random_uuid(),
  bug_id uuid not null references public.bugs(id) on delete cascade,
  from_department text not null default '',
  to_department text not null default '',
  from_user_id uuid references auth.users(id),
  to_user_id uuid references auth.users(id),
  note text not null default '',
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null default '',
  bug_id uuid references public.bugs(id) on delete cascade,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.developers (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 40),
  department text not null check (char_length(department) between 1 and 60),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (name, department)
);

-- 兼容旧版数据库：移除已废弃的提交团队、人员职能和联系方式字段。
alter table public.bugs drop column if exists team;
alter table public.developers drop column if exists role;
alter table public.developers drop column if exists contact;

create index if not exists test_cases_created_at_idx on public.test_cases (created_at desc);
create index if not exists notifications_recipient_idx on public.notifications (recipient_id, is_read, created_at desc);

-- 将旧版严重程度与优先级合并为轻、中、重三个重要程度等级。
alter table public.bugs add column if not exists importance text;
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'bugs' and column_name = 'severity'
  ) and exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'bugs' and column_name = 'priority'
  ) then
    execute $migration$
      update public.bugs
      set importance = case
        when severity in ('blocker', 'critical') or priority in ('urgent', 'high') then 'heavy'
        when severity = 'minor' and priority = 'low' then 'light'
        else 'medium'
      end
      where importance is null
    $migration$;
  else
    update public.bugs set importance = 'medium' where importance is null;
  end if;
end $$;
alter table public.bugs alter column importance set default 'medium';
alter table public.bugs alter column importance set not null;
alter table public.bugs drop constraint if exists bugs_importance_check;
alter table public.bugs add constraint bugs_importance_check check (importance in ('light', 'medium', 'heavy'));
alter table public.bugs drop column if exists severity;
alter table public.bugs drop column if exists priority;

alter table public.bugs add column if not exists assignee_department text not null default '';
alter table public.bugs add column if not exists assignee_id uuid references public.developers(id) on delete set null;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'bugs_assignee_department_length'
  ) then
    alter table public.bugs
      add constraint bugs_assignee_department_length check (char_length(assignee_department) <= 60);
  end if;
end $$;

create index if not exists bugs_status_idx on public.bugs (status);
create index if not exists bugs_created_at_idx on public.bugs (created_at desc);
create index if not exists bugs_assignee_id_idx on public.bugs (assignee_id);
create index if not exists bugs_assignee_department_idx on public.bugs (assignee_department);
create index if not exists developers_department_idx on public.developers (department);

alter table public.bugs enable row level security;
alter table public.developers enable row level security;
alter table public.profiles enable row level security;
alter table public.test_cases enable row level security;
alter table public.assignment_events enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "internal read bugs" on public.bugs;
create policy "internal read bugs"
on public.bugs for select to authenticated
using (true);

drop policy if exists "internal create bugs" on public.bugs;
create policy "internal create bugs"
on public.bugs for insert to authenticated
with check (
  (submitter_id = auth.uid() or submitter_id is null)
  and
  status = 'open'
  and fix_plan = ''
  and assignee = ''
  and resolved_at is null
  and cardinality(attachment_urls) <= 8
);

drop policy if exists "internal update bugs" on public.bugs;
create policy "internal update bugs"
on public.bugs for update to authenticated
using (submitter_id = auth.uid() or follow_up_id = auth.uid() or public.is_admin() or public.current_department() = assignee_department)
with check (
  status in ('open', 'in_progress', 'resolved')
  and char_length(fix_plan) <= 3000
  and char_length(assignee) <= 40
  and char_length(assignee_department) <= 60
);

drop policy if exists "internal read developers" on public.developers;
create policy "internal read developers"
on public.developers for select to authenticated
using (true);

drop policy if exists "internal create developers" on public.developers;
drop policy if exists "admin create developers" on public.developers;
create policy "internal create developers"
on public.developers for insert to authenticated
with check (public.is_admin() and
  active = true
  and char_length(name) between 1 and 40
  and char_length(department) between 1 and 60
);

drop policy if exists "internal update developers" on public.developers;
create policy "internal update developers"
on public.developers for update to authenticated
using (public.is_admin())
with check (
  char_length(name) between 1 and 40
  and char_length(department) between 1 and 60
);

drop policy if exists "team read profiles" on public.profiles;
drop policy if exists "admin manage profiles" on public.profiles;
drop policy if exists "team read test cases" on public.test_cases;
drop policy if exists "team submit test cases" on public.test_cases;
drop policy if exists "review test cases" on public.test_cases;
drop policy if exists "team read assignment events" on public.assignment_events;
drop policy if exists "team create assignment events" on public.assignment_events;
drop policy if exists "read own notifications" on public.notifications;
drop policy if exists "update own notifications" on public.notifications;
create policy "team read profiles" on public.profiles for select to authenticated using (true);
drop policy if exists "admin manage profiles" on public.profiles;
create policy "admin insert member profiles" on public.profiles for insert to authenticated
  with check (public.is_admin() and role <> 'admin');
create policy "admin update member profiles" on public.profiles for update to authenticated
  using (public.is_admin() and role <> 'admin')
  with check (public.is_admin() and role <> 'admin');
create policy "team read test cases" on public.test_cases for select to authenticated using (true);
create policy "team submit test cases" on public.test_cases for insert to authenticated with check (submitter_id = auth.uid());
create policy "review test cases" on public.test_cases for update to authenticated using (submitter_id = auth.uid() or public.is_admin() or public.current_department() = '测试');
create policy "team read assignment events" on public.assignment_events for select to authenticated using (true);
create policy "team create assignment events" on public.assignment_events for insert to authenticated with check (created_by = auth.uid());
create policy "read own notifications" on public.notifications for select to authenticated using (recipient_id = auth.uid() or public.is_admin());
create policy "update own notifications" on public.notifications for update to authenticated using (recipient_id = auth.uid());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'bug-attachments',
  'bug-attachments',
  true,
  10485760,
  array['image/png', 'image/jpeg', 'image/gif', 'image/webp', 'image/bmp', 'image/avif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'test-case-files',
  'test-case-files',
  true,
  20971520,
  array[
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'text/csv',
    'application/pdf',
    'application/zip',
    'application/octet-stream'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "internal upload bug attachments" on storage.objects;
create policy "internal upload bug attachments"
on storage.objects for insert to authenticated
with check (bucket_id = 'bug-attachments');

drop policy if exists "public read bug attachments" on storage.objects;
create policy "public read bug attachments"
on storage.objects for select to authenticated
using (bucket_id = 'bug-attachments');

drop policy if exists "team upload test case files" on storage.objects;
create policy "team upload test case files"
on storage.objects for insert to authenticated
with check (bucket_id = 'test-case-files');

drop policy if exists "team read test case files" on storage.objects;
create policy "team read test case files"
on storage.objects for select to authenticated
using (bucket_id = 'test-case-files');

-- 该方案按需求采用匿名内部访问。正式上线时建议接入 Supabase Auth，
-- 将看板 update 策略限制为 authenticated 开发成员，并关闭公网访问。
